[Users.username1]
password = "$2a$10$QXtQYxDFKwrp67QvcvOZb.GtdKL0YDR.0VeEB2fd0aroqxR0tIf7m"
permissions=["*:*","eth:blockNumber"]
privacyPublicKey = "UqjFQnta8bMFD/qlb6xIpaGTtMR5S8jtyWWl3KB4pQA="



[User.username12]
password = "$2a$10$f7F.ukN67KfkQHiEm08UOeLbuttVr//V8dX1koltgbxdY4.8ndjkm"
permissions =["*:*","eth:blockNumber"]
privacyPublicKey = "R4l0mId31cjRDZaULS+KW2B9p2TVfmBYMf4h2pTaizc="