version: '3.3'
services:
  besu:
    ports:
      - '30303:30303'
      - '8545:8545'
    environment:
      - BESU_RPC_HTTP_ENABLED=true
    image: hyperledger/besu:latest
    container_name: "besu-node1"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/option.toml
    networks:
      customnetwork:
        ipv4_address: 172.21.0.10
volumes:
  .:



