version: '3'
services:
  besu:
    image: hyperledger/besu:latest
    ports:
      - '30305:30303'
      - '8547:8545'
    environment:
      - BESU_RPC_HTTP_ENABLED=true
    container_name: "besu-node3"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/option.toml
    networks:
      customnetwork:
        ipv4_address: 172.21.0.12
volumes:
  .: