[Users.username4]
password = "$2a$10$sWytI4WNUYHUuzqPmlYeJuV12d/bFVi6zvTgbWaOrQhtSgQGDaywm"
permissions=["net:*","eth:blockNumber"]
privacyPublicKey = "RT+Lvk9rek/1WR5m8bcNTvU0fSwhri0SNalUvfwAFio="




