version: '3'
services:
  besu:
    image: hyperledger/besu:latest
    ports:
      - '30306:30303'
      - '8548:8545'
    environment:
      - BESU_RPC_HTTP_ENABLED=true
    container_name: "node4"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/option.toml
    networks:
      customnetwork:
        ipv4_address: 172.21.0.13
volumes:
  .:
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.21.0.0/16