data-path = "/usr/app/data"


bootnodes = ["enode://f857669250cee37ffcac3fe5d4f06f3db58c288780d7e432a0a9836e92c6071d9fd82ebf85f75a5acd2acb58fb466c2069dcb5ffbc8249f4ec5446708582cf6c@172.21.0.10:30303"]


genesis-file = "/usr/app/genesis.json"

rpc-http-authentication-enabled = true

#rpc-http-authentication-jwt-public-key-file= "publicKey.pem"

rpc-http-enabled = true

rpc-http-authentication-credentials-file="/usr/app/auth.toml"

p2p-port=30306

rpc-http-api=["ETH","NET","IBFT","EEA","PRIV"]

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

privacy-enabled = true

privacy-multi-tenancy-enabled = true

min-gas-price=0

privacy-url="http://localhost:9402"