version: '3'
services:
  tessera:
    image: quorumengineering/tessera:latest
    container_name: "tessera-node3"
    volumes:
    - .:/usr/app/
    working_dir: /usr/app/
    command:
        --configfile tessera.conf
    networks:
      customnetwork:
        ipv4_address: 172.21.0.16
volumes:
  .:
